<a href="https://colab.research.google.com/github/cyamize/AI/blob/main/numpy_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np 

In [2]:
np.__version__

'1.19.5'

### 1D ndarray

In [3]:
nd1 = np.array([1, 2, 3, 4])

In [4]:
print(nd1)

[1 2 3 4]


In [5]:
nd1.ndim

1

### 2D ndarray

In [6]:
nd2 = np.array([[1, 2, 3], [4, 5, 6]])

In [7]:
print(nd2)

[[1 2 3]
 [4 5 6]]


In [8]:
nd2.ndim

2

### 3D ndarray

In [9]:
nd3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], 
                 [[13, 14, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]])

In [10]:
print(nd3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]


In [11]:
nd3.ndim

3

### 4D ndarray

In [12]:
nd4 = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], 
                [[[9, 10], [11, 12]], [[13, 14], [15, 16]]], 
                [[[17, 18], [19, 20]], [[21, 22], [23, 24]]]])      

In [13]:
print(nd4)

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]


 [[[17 18]
   [19 20]]

  [[21 22]
   [23 24]]]]


In [14]:
nd4.ndim

4

---

### dtype

In [15]:
nd1 = np.array([1.0, 2.1, 3.0, 4.2])

In [16]:
nd1.dtype # float64로 default 할당

dtype('float64')

In [17]:
nd2 = np.array([[1, 2, 3], [4, 5, 6]])

In [18]:
nd2.dtype # int32로 default 할당

dtype('int64')

In [19]:
nd2 = np.array([[1, 2, 3], [4, 5, 6]], dtype = np.float32)

In [20]:
nd2.dtype

dtype('float32')

In [21]:
nd2 = np.array([[1, 2, 3], [4, 5, 6]], dtype = 'float64')

In [22]:
nd2.dtype # ndarray 자료형 확인

dtype('float64')

In [23]:
nd2.astype(np.float32) # ndarray 자료형 변환

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [24]:
nd2.astype('float64')

array([[1., 2., 3.],
       [4., 5., 6.]])

In [25]:
nd2.dtype

dtype('float64')

In [26]:
print(nd1.dtype, nd2.dtype)

float64 float64


In [27]:
nd1 = nd1.astype('int32')

In [28]:
nd1.dtype

dtype('int32')

---

### shape

In [29]:
nd1.shape # 입력데이터의 shape확인 

(4,)

In [30]:
nd2.shape

(2, 3)

In [31]:
nd3.shape

(2, 4, 3)

In [32]:
nd4.shape

(3, 2, 2, 2)

---

### size

In [33]:
nd1.size # size 변수를 이용하여 size확인

4

In [34]:
nd2.size

6

In [35]:
nd3.size

24

In [36]:
nd4.size

24

---

### reshape

In [37]:
nd3.shape

(2, 4, 3)

In [38]:
nd4.shape

(3, 2, 2, 2)

In [39]:
# 입력데이터의 shape가 불일치한 경우, 이를 맞추기 위해 shape의 변환 과정 필요
# reshape 변수를 이용하여 shape의 변환이 가능
# 동일 차원내 변환 및 이종 차원간 변환이 가능하며, ndarray의 size가 동일해야 reshape 가능
new_nd3 = nd4.reshape((2,4,3))

In [40]:
new_nd3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [41]:
new_nd3.shape

(2, 4, 3)

In [42]:
new_nd2 = nd3.reshape((4,6))

In [43]:
new_nd2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [44]:
new_nd2.shape

(4, 6)

In [45]:
new_nd1 = nd3.reshape((24,))

In [46]:
new_nd1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [47]:
new_nd1.shape

(24,)

### zeros

In [48]:
np.zeros((4, 3)) # shape의 모양대로 0을 채운 ndarray 생성

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### ones

In [49]:
np.ones((3, 4)) # shape의 모양대로 1으로 채운 ndarray 생성

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### arange

In [50]:
np.arange(12) # pythone의 range함수와 동일하다

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [51]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [52]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [53]:
np.arange(12).reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

---

### vectorize operaion

In [73]:
# ndarray는 벡터화 연산(vectorized operation)을 지원
# 별도의 반복문을 사용하지 않고 같은 위치의 값 끼리 반복 연산 가능

In [54]:
op1 = np.array([1, 2, 3, 4, 5, 6])

In [55]:
op1

array([1, 2, 3, 4, 5, 6])

In [56]:
op1 = op1.reshape(3, 2)

In [57]:
op1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [58]:
op2 = np.array([2] * 6)

In [59]:
op2

array([2, 2, 2, 2, 2, 2])

In [60]:
op2 = op2.reshape(3, 2)

In [61]:
op2

array([[2, 2],
       [2, 2],
       [2, 2]])

In [62]:
op1 + op2

array([[3, 4],
       [5, 6],
       [7, 8]])

In [63]:
op1.shape

(3, 2)

In [64]:
op1 - op2

array([[-1,  0],
       [ 1,  2],
       [ 3,  4]])

In [65]:
op1 * op2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [66]:
op1 / op2

array([[0.5, 1. ],
       [1.5, 2. ],
       [2.5, 3. ]])

---

### broadcasting

In [74]:
# ndarray의 브로드캐스팅(broadcasting)은 연산이 가능한 형태로
# 자동 reshape한 후 반복된 값으로 할당하여 연산을 수행한다.

In [67]:
np.arange(3)

array([0, 1, 2])

In [68]:
np.arange(3) + 5

array([5, 6, 7])

In [69]:
np.ones((3, 3)) 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [70]:
np.ones((3, 3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [71]:
np.arange(3).reshape(3,1)

array([[0],
       [1],
       [2]])

In [72]:
np.arange(3).reshape(3,1) + np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])