<a href="https://colab.research.google.com/github/cyamize/AI/blob/main/train_mnist.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 데이터 로드

In [18]:
import warnings
warnings.filterwarnings('ignore')

In [19]:
!pip install tensorflow

In [20]:
from keras.datasets import mnist

In [21]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [22]:
train_images.shape

(60000, 28, 28)

In [23]:
test_images.shape

(10000, 28, 28)

In [24]:
train_labels.shape

(60000,)

In [25]:
test_labels.shape

(10000,)

## 데이터 전처리

In [26]:
train_images = train_images.reshape((60000, 28 * 28))
test_images = test_images.reshape((10000, 28 * 28))

In [27]:
train_images.shape #(샘플개수, 28*28)

(60000, 784)

In [28]:
test_images.shape

(10000, 784)

### 정규화

In [29]:
train_images[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  18,  18,  18,
       126, 136, 175,  26, 166, 255, 247, 127,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 154, 17

In [30]:
train_images = train_images.astype('float32') / 255
test_images = test_images.astype('float32') / 255

In [31]:
train_images[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

### One-hot 인코딩

In [32]:
train_labels[0]

5

In [33]:
train_labels.shape

(60000,)

In [34]:
from tensorflow.keras.utils import to_categorical

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [35]:
train_labels[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [36]:
train_labels.shape

(60000, 10)

## 네트워크 모델 설계

In [37]:
from keras import models
from keras import layers

In [38]:
model = models.Sequential()
model.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
model.add(layers.Dense(10, activation='softmax'))

In [39]:
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [40]:
 model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 512)               401920    
_________________________________________________________________
dense_1 (Dense)              (None, 10)                5130      
Total params: 407,050
Trainable params: 407,050
Non-trainable params: 0
_________________________________________________________________


## 모델 훈련(training)

In [41]:
model.fit(train_images, train_labels, epochs=5, batch_size=64)

Epoch 1/5
938/938 [==============================] - 19s 4ms/step - loss: 0.3765 - accuracy: 0.8915
Epoch 2/5
938/938 [==============================] - 3s 4ms/step - loss: 0.0962 - accuracy: 0.9712
Epoch 3/5
938/938 [==============================] - 3s 3ms/step - loss: 0.0614 - accuracy: 0.9810
Epoch 4/5
938/938 [==============================] - 3s 4ms/step - loss: 0.0445 - accuracy: 0.9873
Epoch 5/5
938/938 [==============================] - 3s 4ms/step - loss: 0.0322 - accuracy: 0.9907


## 모델 평가

In [42]:
test_loss, test_acc = model.evaluate(test_images, test_labels)

313/313 [==============================] - 1s 3ms/step - loss: 0.0800 - accuracy: 0.9793


In [43]:
print('test_acc:', test_acc)

test_acc: 0.9793000221252441
